colors:
  primary:
    foreground: '#e4e4ef'    
    background: "#181818"

  cursor:
    text: "#181818"
    cursor: "#ffdd33"

  normal:
    black:   '#000000'
    red:     '#f43841'
    green:   '#73c936'
    yellow:  '#ffdd33'
    blue:    '#5f627f'
    magenta: '#9e95c7'
    cyan:    '#5f627f'
    white:   '#ffffff'

  bright:
    black:   '#282828'
    red:     '#ff4f58'
    green:   '#73c936'
    yellow:  '#ffdd33'
    blue:    '#96a6c8'
    magenta: '#9e95c7'
    cyan:    '#96a6c8'
    white:   '#ffffff'

font:
  size: 13
  normal:
    family: "DejaVu Sans Mono"
